<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Authors>RzR</Authors>
    <Copyright>RzR</Copyright>
    <Owners>RzR</Owners>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageIcon>PackageIcon.png</PackageIcon>
    <NoWarn>$(NoWarn);CS8032</NoWarn>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageTags>Export;CSV;XLSX;Excel;Generate</PackageTags>
    <RepositoryUrl>https://github.com/I-RzR-I/DynamicExcelProvider</RepositoryUrl>
    <PackageProjectUrl>https://github.com/I-RzR-I/DynamicExcelProvider</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageDescription>Export data to Excel format in an easier mode and with dynamic results.</PackageDescription>
    <Summary>Export data to Excel format in an easier mode and with dynamic results.</Summary>
    <PackageTitle>RzR.Shared.Export.DynamicExcelProvider</PackageTitle>
    <Title>RzR.Shared.Export.DynamicExcelProvider</Title>
    <LangVersion>9.0</LangVersion>
    <RepositoryType>GIT</RepositoryType>
    <Language>en-US</Language>
    <PackageIconUrl />
    <DebugType>Full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\shared\GeneralAssemblyInfo.cs" Link="Properties\GeneralAssemblyInfo.cs" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\assets\PackageIcon.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="..\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RzR.ResultMessage" Version="3.0.0.6928" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="RzR.Extensions.Domain" Version="6.0.0.8301" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>

  <ProjectExtensions>
    <VisualStudio>
      <UserProperties BuildVersion_StartDate="2024/02/10" />
    </VisualStudio>
  </ProjectExtensions>
  <!--<Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="PowerShell -NoProfile -ExecutionPolicy unrestricted -file $(SolutionDir)../build/pack.ps1 $(ConfigurationName)" />
  </Target>-->
</Project>